services:
  db:
    container_name: akademia-dev-db
    image: postgres:16
    environment:
      POSTGRES_DB: akdemya
      POSTGRES_USER: ak_user
      POSTGRES_PASSWORD: ak_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks: 
      - cluster_network 

  api:
    container_name: akademia-dev-api
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/akdemya
      SPRING_DATASOURCE_USERNAME: ak_user
      SPRING_DATASOURCE_PASSWORD: ak_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_PROFILES_ACTIVE: dev
      SPRING_SQL_INIT_MODE: never
      JWT_SECRET: "akdemya-secret-key-please-change-me-32bytes"
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - cluster_network

  web:
    container_name: akademia-dev-web
    build: ./frontend
    environment:
      VITE_API_URL: http://192.168.1.175:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - cluster_network

volumes:
  pgdata:
networks:
  cluster_network:
    external: true
