services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: akdemya
      POSTGRES_USER: ak_user
      POSTGRES_PASSWORD: ak_pass
    ports:
      - "6543:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql
    networks:
      - prod_network

  api:
    image: akademia-api:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/akdemya
      SPRING_DATASOURCE_USERNAME: ak_user
      SPRING_DATASOURCE_PASSWORD: ak_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    ports:
      - "8082:8080"
    networks:
      - prod_network

  web:
    image: akademia-web:1.0.0
    environment:
      VITE_API_URL: http://localhost:8082
    ports:
      - "5173:3000"
    depends_on:
      - api
    networks:
      - prod_network

volumes:
  pgdata_prod:

networks:
  prod_network:
    driver: bridge
