export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  syllabuses: '/syllabuses',
  syllabusSubjects: (id: string) => `/syllabuses/${id}/subjects`,
  syllabusExamBuilder: (id: string) => `/syllabuses/${id}/exam-builder`,
  subjects: '/subjects',
  subjectBuilder: (subjectId: string) => `/subjects/${subjectId}/builder`,
  examRunner: '/exam',
  examAttempt: (attemptId: string) => `/exams/attempts/${attemptId}`,
  examResult: '/result',
  settings: '/settings',
  manage: '/manage',
  profile: '/profile',
  flashcards: '/flashcards',
  flashcardsStudy: '/flashcards/study',
  flashcardsHistory: '/flashcards/history',
  flashcardsExamine: '/flashcards/examine',
  rag: '/rag',
  syllabusSales: '/temario',
  subalternoGva: '/temario/subalterno-gva',
  oauth2Callback: '/oauth2/callback'
} as const;
