#!/usr/bin/env bash
set -euo pipefail

VERSION=""
SPRINT_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      VERSION="$2"
      shift 2
      ;;
    --sprint)
      SPRINT_ID="$2"
      shift 2
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$VERSION" || -z "$SPRINT_ID" ]]; then
  echo "Usage: $0 --version <x.y.z> --sprint <id>" >&2
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree not clean. Commit or stash changes first." >&2
  exit 1
fi

: "${JIRA_BASE:?Missing JIRA_BASE}"
: "${JIRA_EMAIL:?Missing JIRA_EMAIL}"
: "${JIRA_TOKEN:?Missing JIRA_TOKEN}"
: "${GITHUB_TOKEN:?Missing GITHUB_TOKEN}"
: "${GITHUB_REPO:?Missing GITHUB_REPO (e.g. guilu/akadem.ia)}"

export VERSION
export SPRINT_ID

python - <<'PY'
import base64, json, os, sys, urllib.request, urllib.parse, datetime

jira_base = os.environ['JIRA_BASE']
email = os.environ['JIRA_EMAIL']
token = os.environ['JIRA_TOKEN']
version = os.environ['VERSION']
sprint_id = os.environ['SPRINT_ID']

auth = base64.b64encode(f"{email}:{token}".encode()).decode()

jql_open = f"sprint={sprint_id} AND statusCategory!=Done"
url = f"{jira_base}/rest/api/3/search/jql?jql={urllib.parse.quote(jql_open)}&fields=key"
req = urllib.request.Request(url)
req.add_header('Authorization', f'Basic {auth}')
req.add_header('Accept','application/json')
with urllib.request.urlopen(req) as r:
    data = json.loads(r.read().decode())

if data.get('issues'):
    keys = ', '.join([i['key'] for i in data['issues']])
    print(f"Sprint has open issues: {keys}")
    sys.exit(2)

jql_done = f"sprint={sprint_id} AND statusCategory=Done ORDER BY key ASC"
url = f"{jira_base}/rest/api/3/search/jql?jql={urllib.parse.quote(jql_done)}&fields=key,summary,issuetype"
req = urllib.request.Request(url)
req.add_header('Authorization', f'Basic {auth}')
req.add_header('Accept','application/json')
with urllib.request.urlopen(req) as r:
    data = json.loads(r.read().decode())

issues = data.get('issues', [])

today = datetime.date.today().isoformat()
lines = [f"## v{version} - {today}", ""]
for issue in issues:
    key = issue['key']
    summary = issue['fields']['summary']
    url = f"{jira_base}/browse/{key}"
    lines.append(f"- [{key}]({url}) {summary}")
lines.append("")

changelog_path = os.path.join(os.getcwd(), "CHANGELOG.md")
if os.path.exists(changelog_path):
    with open(changelog_path, 'r', encoding='utf-8') as f:
        existing = f.read().strip()
else:
    existing = ""

content = "\n".join(lines).strip()
if existing:
    content = content + "\n\n" + existing + "\n"
else:
    content = content + "\n"

with open(changelog_path, 'w', encoding='utf-8') as f:
    f.write(content)

readme_path = os.path.join(os.getcwd(), "README.md")
with open(readme_path, 'r', encoding='utf-8') as f:
    readme = f.read()

if "Version:" in readme:
    import re
    readme = re.sub(r"Version:.*", f"Version: {version}", readme, count=1)
else:
    lines = readme.splitlines()
    if lines:
        lines.insert(1, f"Version: {version}")
    readme = "\n".join(lines)

with open(readme_path, 'w', encoding='utf-8') as f:
    f.write(readme)
PY

release_branch="release/${VERSION}"

git checkout -b "$release_branch"

perl -0777 -i -pe "s/version = '([^']+)'/version = '${VERSION}'/" backend/build.gradle
node -e "const fs=require('fs'); const p='frontend/package.json'; const data=JSON.parse(fs.readFileSync(p,'utf8')); data.version='${VERSION}'; fs.writeFileSync(p, JSON.stringify(data, null, 2)+'\n');"

perl -0777 -i -pe "s/akademia-api:\d+\.\d+\.\d+/akademia-api:${VERSION}/" dist/docker-compose-prod.yaml
perl -0777 -i -pe "s/akademia-web:\d+\.\d+\.\d+/akademia-web:${VERSION}/" dist/docker-compose-prod.yaml

git add CHANGELOG.md README.md backend/build.gradle frontend/package.json

git add -f dist/docker-compose-prod.yaml

git commit -m "chore(release): v${VERSION}"

echo "Building docker images..."

docker build -t akademia-api:${VERSION} backend

docker build -t akademia-web:${VERSION} frontend

echo "Release branch prepared: ${release_branch}"

# push branch and open PR

git push -u origin "$release_branch"

python - <<'PY'
import json, os, urllib.request

token = os.environ['GITHUB_TOKEN']
repo = os.environ['GITHUB_REPO']
version = os.environ['VERSION']
head = f"release/{version}"

payload = {
    "title": f"release: v{version}",
    "head": head,
    "base": "main",
    "body": f"Release v{version}\n\nGenerated by release script."
}

req = urllib.request.Request(f"https://api.github.com/repos/{repo}/pulls", data=json.dumps(payload).encode(), method='POST')
req.add_header('Authorization', f'token {token}')
req.add_header('Accept','application/vnd.github+json')
with urllib.request.urlopen(req) as resp:
    data = json.loads(resp.read().decode())
print(data['html_url'])
PY

echo "NOTE: Tag v${VERSION} should be created when merging ${release_branch} into main."
