spring.flyway.locations=classpath:db/migration,classpath:db/migration-dev

app.flashcards.learning-steps-minutes=1,10
app.flashcards.easy-interval-days=4
app.flashcards.review-again-relearn-minutes=10
