spring.application.name=akdemya-api
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
# spring.jpa.defer-datasource-initialization=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
security.jwt.secret=${JWT_SECRET}